In [1]:
# Importing models

import bagging_decision_trees
import decision_trees
import gradient_boosting
import knn
import logistic_regression
import random_forest
import svm_linear
import svm_rbf

# Importing libraries for transforming data
import numpy as np
import pandas as pd
import clean_split_data

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [4]:
cleaned = clean_split_data.clean_data(data)
X_train, X_test, y_train, y_test = clean_split_data.split_data(cleaned)

In [5]:
test_data = pd.read_csv('test_file.csv')

In [6]:
test_data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0  8510426         B       13.540         14.36           87.46      566.3   
1  8510653         B       13.080         15.71           85.63      520.0   
2  8510824         B        9.504         12.44           60.34      273.9   
3  8511133         M       15.340         14.26          102.50      704.4   
4   851509         M       21.160         23.04          137.20     1404.0   
5   852552         M       16.650         21.38          110.00      904.6   
6   852631         M       17.140         16.40          116.00      912.7   
7   852763         M       14.580         21.53           97.41      644.8   
8   852781         M       18.610         20.25          122.10     1094.0   
9   852973         M       15.300         25.27          102.40      732.4   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.09779           0.08129         0.06664              0.04781   
1          0.10750           0.12700         0.04568              0.03110   
2          0.10240           0.06492         0.02956              0.02076   
3          0.10730           0.21350         0.20770              0.09756   
4          0.09428           0.10220         0.10970              0.08632   
5          0.11210           0.14570         0.15250              0.09170   
6          0.11860           0.22760         0.22290              0.14010   
7          0.10540           0.18680         0.14250              0.08783   
8          0.09440           0.10660         0.14900              0.07731   
9          0.10820           0.16970         0.16830              0.08751   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         15.11          19.26            99.70       711.2   
1  ...         14.50          20.49            96.09       630.5   
2  ...         10.23          15.66            65.13       314.9   
3  ...         18.07          19.08           125.10       980.9   
4  ...         29.17          35.59           188.00      2615.0   
5  ...         26.46          31.56           177.00      2215.0   
6  ...         22.25          21.40           152.40      1461.0   
7  ...         17.62          33.21           122.40       896.9   
8  ...         21.31          27.26           139.90      1403.0   
9  ...         20.27          36.71           149.30      1269.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1440             0.1773          0.23900               0.12880   
1            0.1312             0.2776          0.18900               0.07283   
2            0.1324             0.1148          0.08867               0.06227   
3            0.1390             0.5954          0.63050               0.23930   
4            0.1401             0.2600          0.31550               0.20090   
5            0.1805             0.3578          0.46950               0.20950   
6            0.1545             0.3949          0.38530               0.25500   
7            0.1525             0.6643          0.55390               0.27010   
8            0.1338             0.2117          0.34460               0.14900   
9            0.1641             0.6110          0.63350               0.20240   

   symmetry_worst  fractal_dimension_worst  
0          0.2977                  0.07259  
1          0.3184                  0.08183  
2          0.2450                  0.07773  
3          0.4667                  0.09946  
4          0.2822                  0.07526  
5          0.3613                  0.09564  
6          0.4066                  0.10590  
7          0.4264                  0.12750  
8          0.2341                  0.07421  
9          0.4027                  0.09876  

[10 rows x 32 columns]

In [7]:
def average_ensemble(csv_name):
    '''
    Takes user input data and returns excel with diagnosis of each patient. User must input csv file name including
    .csv file type as a string.
    '''
    data = pd.read_csv(str(csv_name))
    predictions_df = pd.DataFrame(columns=['Sample ID', 'Diagnosis'])
    list_of_models = [bagging_decision_trees, decision_trees, gradient_boosting,
                      knn, logistic_regression, random_forest, svm_linear, svm_rbf]
    list_of_votes = np.zeros(len(data))   
    for model in list_of_models:
        X = data[model.feature_names()]
        list_of_votes += (model.predict(X))
        print(list_of_votes)
    index = 0
    for case in list_of_votes:
        average_vote = case / len(list_of_models)
        last_row = len(predictions_df)
        if average_vote < 0.5:
            predictions_df.loc[last_row] = [data['id'][index], 'B']
        else:
            predictions_df.loc[last_row] = [data['id'][index], 'M']
        index += 1
    predictions_df.set_index('Sample ID', inplace=True)
    
    return predictions_df
#     return predictions_df.to_csv('Sample Diagnosis Results.csv', index=False)

In [8]:
average_ensemble('test_file.csv')

[0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 2. 2. 2. 2. 2. 2. 2.]
[0. 0. 0. 3. 3. 3. 3. 3. 3. 3.]
[0. 0. 0. 3. 4. 4. 4. 4. 4. 4.]
[0. 0. 0. 4. 5. 5. 5. 5. 5. 5.]
[0. 0. 0. 5. 6. 6. 6. 6. 6. 6.]
[0. 0. 0. 6. 7. 7. 7. 7. 7. 7.]
[0. 0. 0. 7. 8. 8. 8. 8. 8. 8.]


Diagnosis
Sample ID          
8510426           B
8510653           B
8510824           B
8511133           M
851509            M
852552            M
852631            M
852763            M
852781            M
852973            M